### ISSUE TITLE
Annotations not showing

### ISSUE THREAD

**Issue by mauricekleine** [chartjs/chartjs-plugin-annotation#47] opened 2016-12-20 15:09 UTC
**Versions**
chart.js v2.4.0
chartjs-plugin-annotation v0.5.2
(angular v1.6.0)

**What is going wrong?**
I used to generate the chart data in PHP and render it like this: 

```
<div class="chart-container">
  <canvas id="chart"></canvas>
 </div>

<script type="text/javascript">
  window.onload = function() {
    var ctx = document.getElementById("chart").getContext("2d");
    window.chart = new Chart(ctx, <?php echo $chart["config"]; ?>);
  };
</script>
```

Annotations were shown as expected and all was good. But now I've separated the front end from the back end and I've written an Angular directive to aid in the generation of a chart like this:

```
import Chart from 'chart.js';
import 'chartjs-plugin-annotation';

class ChartController {
  $onChanges(changes) {
    if (changes.chartData && changes.chartData.currentValue.data) {
      if (this.chart) {
        this.chart.destroy();
      }
      this.chart = new Chart('chart', changes.chartData.currentValue);

      console.log(this.chart);
    }
  }
}

export default ChartController;
```

The chartData object is the same as in the PHP version. However, the annotations are not drawn. The console log does show that the annotations are bounded to the Chart instance:

![screenshot from 2016-12-20 16-01-56](https://cloud.githubusercontent.com/assets/10089969/21355285/ad6d1fd0-c6cd-11e6-9809-d2c656508fca.png)

I can not find anything about this issue. Does anybody have an idea on how to fix this?

Thanks in advance!

**Comment by compwright** [comment] 2016-12-20 15:13
What is in the `chartInstance.annotation.elements` property? Also, this will be a lot easier to work through if you can provide a CodePen or jsfiddle that reproduces the issue.

**Comment by mauricekleine** [comment] 2016-12-20 17:44
I've created a jsfiddle that reproduces this issue: https://jsfiddle.net/4rdrm9fz/

The contents of `chartInstance.annotation.elements` in my application is in the screenshot below:

![screenshot from 2016-12-20 18-22-08](https://cloud.githubusercontent.com/assets/10089969/21361428/471783e4-c6e4-11e6-8083-35b7353007fa.png)

**Comment by compwright** [comment] 2016-12-20 19:50
There's definitely a render bug with some scale types. There are known issues currently with category, time, and even some linear scale configurations. We'll get these fixed at some point. Feel free to submit PRs if you feel like tracking any of these down. I suspect the issue lies in either the canvas clipping or in the scale value to pixel translation, or both.

For now, I was able to get your example working with some configuration changes. Note that if you specify the `scaleID` for an annotation, you need to explicitly configure the scale with that ID, and if you're doing vertical lines, you need to specify your line values using `[{x:Number, y:Number}, ...]` instead of a simple array of values.

https://jsfiddle.net/rnvqLgvu/

**Comment by mauricekleine** [comment] 2016-12-21 09:49
Thank you for your solution, it works for me. If I can find a fix for this issue, I will submit a PR. 

One other thing, if I add the label below to the annotation in your jsfiddle, the label is not shown. If I remove the `position` attribute, it does show. So there's also in issue with the labels, but it might be related to the one mentioned above.

```
label: {
  content: 'label',
  enabled: true,
  position: 'top',
},
```

**Comment by compwright** [comment] 2017-05-20 15:11
Duplicate of #35

**Closed by compwright** 2017-05-20 15:11 UTC
Labels: duplicate
