### ISSUE TITLE
Should calling chart.update() after modifying annotation options trigger changes?

### ISSUE THREAD

**Issue by dalanmiller** [chartjs/chartjs-plugin-annotation#115] opened 2018-04-02 02:15 UTC
I'm trying to change the line annotations I've created with updates to the datasets. Is it possible to modify the annotation options in place and then observe changes after `chart.update()`? I'm not currently seeing this but may be doing something wrong or should be replacing the `chart.options.annotation` object completely.

**Comment by veggiesaurus** [comment] 2018-04-03 15:47
I had some trouble with getting the options to propagate correctly, but in the end, this worked for me: 
```
chart.annotation.elements['my-annotation-id'].options.value = newValue;
chart.update();
```

See this [jsfiddle](https://jsfiddle.net/veggiesaurus/6ze2m05d/43/) for an example. 
_[Note that this is actually a test for a PR I've worked on, so don't expect `chart.render()` to update annotations until #116 is merged]_

**Comment by leafyeh7** [comment] 2018-04-05 20:37
I can confirm the answer from @veggiesaurus works.  I am using version 2.7.2 Chart.js and 0.5.3 chartjs-plugin-annotation.

**Comment by sht5** [comment] 2018-12-31 08:18
@veggiesaurus your a life saver

**Comment by dnsudhir** [comment] 2019-08-16 09:57
i am having the same problem

chart.options.annotation.annotations[0]['value'] =newAverageValue;
this.chart.options.annotation.annotations[0]['label'] = {
                          content: 'Average: ' + newAverageValue.toFixed(2),
                          enabled: true
                        };
chart.update();

chart js not updating the label content event after chart.update();

**Comment by oudcheikh** [comment] 2020-01-08 16:50
I have the same problem,
Has anyone find why it not work well ?

**Comment by frederikheld** [comment] 2020-03-07 22:20
> I had some trouble with getting the options to propagate correctly, but in the end, this worked for me:
> 
> ```
> chart.annotation.elements['my-annotation-id'].options.value = newValue;
> chart.update();
> ```
> 
> See this [jsfiddle](https://jsfiddle.net/veggiesaurus/6ze2m05d/43/) for an example.
> _[Note that this is actually a test for a PR I've worked on, so don't expect `chart.render()` to update annotations until #116 is merged]_

OMG! You're my hero! I spen't so many hours to figure this out. Thanks for your work!

What I don't really understand is why accessing the value doesn't follow the structure of the chart object. Why did you chose this approach?

**Comment by frederikheld** [comment] 2020-03-07 22:36
For everyone who's fiddling around with this like me: It's also possible to update the content of an annotation label in the same way :-)

```javascript
// update data:
myChart.data.datasets = formatChartData(newData)

// update mean annotation:
myChart.annotation.elements['mean-value'].options.value = this.calculateMean(newData)
myChart.annotation.elements['mean-value'].options.label.content = 'mean = ' + Math.round(this.calculateMean(this.chartData) * 100) / 100

// re-render chart:
myChart.update()
```

In this example I'm drawning an horizontal line that shows the mean value of a bar chart.

![chartjs_mean](https://user-images.githubusercontent.com/11460463/76153430-39f25880-60cc-11ea-949a-2fcaace8b9f3.png)

**Comment by etimberg** [comment] 2021-03-07 23:58
I believe this is working on the latest code with chart.js v3.0.0-beta.13. We changed how options are resolved to remove merging.

**Closed by etimberg** 2021-03-07 23:58 UTC
Labels: bug

**Comment by Cristy94** [comment] 2021-08-04 13:21
I managed to make it work, the only thing that the TS definitions didn't properly work, so I had to use `as any`.

```
                                        enter: (context) => {
                                            const id = context.element.options.id!;
                                            ((context.chart.options.plugins!.annotation!.annotations as any)[id] as AnnotationOptions).borderColor = 'blue';
                                            context.chart.update();
                                            context.chart.canvas.style.cursor = 'pointer';
                                        },
```

**Comment by marcoruval** [comment] 2022-06-13 16:58
I also tried changing the value directly onto the _context_ object but nothing happened until I access the **AnnotationOptions** the way @Cristy94 suggested above.

**Comment by stockiNail** [comment] 2022-06-13 22:34
Assuming you are using version 1.x, what @Cristy94 is proposing is correct if you want to change the original configuration and apply it on the chart. The `chart.update()` is needed when you change the original configuration..
Nevertheless, the best thing, based on above use case to change the `borderColor` when the mouse over the annotation, is to change the element options and invoke the `chart.draw()` instead of `chart.update()`.

When you change the element options you shouldn't invoke chart.update because the update will read the original plugin configuration (not update changing the element options) and reapply all config to the plugin. 

The correct code should be:

```javascript
  enter: (context) => {
      context.element.options.borderColor = 'blue';
      context.chart.draw();
  },
```

This is also faster because only redrawing is invoked. See the sample https://www.chartjs.org/chartjs-plugin-annotation/latest/samples/line/labelVisibility.html

Going to new version (2.x), you can have a look how the new events hooks signatures are changed (#717) and returning a boolean the chart.draw will be invoked directly by Chart.js. You can also have a look to the current development oicumentation https://www.chartjs.org/chartjs-plugin-annotation/master/guide/configuration.html#events

Version 2.x

```javascript
  enter: (context) => {
      context.element.options.borderColor = 'blue';
      return true;
  },
```
