### ISSUE TITLE
Can I change z-index property of the labels?

### ISSUE THREAD

**Issue by cohenu** [chartjs/chartjs-plugin-annotation#147] opened 2018-12-31 17:01 UTC
Hey all,
I have multiple average lines on the chart and when they are close to each other I want the labels on top of the lines not behind them. is there an option to control this behavior ?

**Comment by cohenu** [comment] 2019-01-11 15:11
example of the problem I'm trying to solve : https://i.imgur.com/cejmWE9.png

**Comment by AmlisPanda** [comment] 2019-12-18 14:10
Same !

**Comment by joshkel** [comment] 2020-10-28 20:29
This looks like a duplicate of #94; see #161.

**Comment by etimberg** [comment] 2021-03-06 22:42
Closing as duplicate

**Closed by etimberg** 2021-03-06 22:42 UTC
