### ISSUE TITLE
Misaligned box annotation vs category label

### ISSUE THREAD

**Issue by Techn1x** [chartjs/chartjs-plugin-annotation#149] opened 2019-01-21 05:09 UTC
I have a chart with an X axis that is of type category (and has various labels for that)
`labels = ["10 Jan", "11 Jan", "12 Jan", "13 Jan", ...]`
My goal is to highlight weekend dates

I've been using strings for `xMin` and `xMax` and it draws the box - but instead of drawing the box from label edge to edge like it should, it draws from the center, like so (xMin = "12 Jan", xMax = "13 Jan")
![untitled](https://user-images.githubusercontent.com/1049837/51454014-47e0ff00-1d8e-11e9-9363-da5d1d42130d.png)

The codepen used to demo this plugin has a similar setup, and it works correctly (annotation is edge to edge of each category). However, when I updated the ChartJS version on that codepen from 2.5.0 to 2.7.0, it had the same issue (annotation starts from center)! So I suspect something has changed in ChartJS to break this part of the plugin
https://codepen.io/compwright/pen/mmQMrZ

Note that this is different to the issue outlined here https://github.com/chartjs/chartjs-plugin-annotation/issues/131 where the poster was just not using string xmin/xmax values.

**Comment by Techn1x** [comment] 2019-01-21 05:50
Looks like this was mentioned here;
https://github.com/chartjs/chartjs-plugin-annotation/issues/98

**Comment by curiousPup** [comment] 2019-08-12 13:29
it's been a while this issue has been floating. Is this repository even being maintained ?

**Comment by etimberg** [comment] 2021-03-06 22:41
Duplicate of #98

**Closed by etimberg** 2021-03-06 22:41 UTC
Labels: bug, duplicate
