### ISSUE TITLE
Cant draw vertical line graph with latest version?

### ISSUE THREAD

**Issue by sahilweb6** [chartjs/chartjs-plugin-annotation#68] opened 2017-05-18 10:02 UTC
Hello! Trying to draw multiple vertical lines in a line graph. Horizontal lines works as intended, but as you can see in this fiddle (http://stackoverflow.com/questions/44041583/vertical-line-with-annotation-plugin-and-labels-in-chart-js) vertical lines does not work.
This work on value but not string like year 5.. how to make it work?

**Comment by compwright** [comment] 2017-05-20 14:22
Support for string labels will be added in a future release. Currently the plugin only works for numeric axis values.

**Comment by compwright** [comment] 2017-05-20 15:08
Duplicate of #47

**Closed by compwright** 2017-05-20 15:08 UTC
Labels: duplicate
