### ISSUE TITLE
JS-Error in use with chart doughnut on the same page

### ISSUE THREAD

**Issue by PureDude** [chartjs/chartjs-plugin-annotation#63] opened 2017-04-26 13:29 UTC
If I render a doughnut-chart on the same page with annotation-plugin I get the following JS-Error and the chart is not shown: **TypeError: t.scales is undefined**
When I remove the annotation plugin chart is rendered. You can see it here:
https://codepen.io/PureDude/pen/JNbVqL
Any idea what this can be?

**Comment by etimberg** [comment] 2017-04-26 22:53
This is likely because the doughnut chart only has one axis and doesn't create a `Chart.scales` property. Happy to look at a PR fixing this

**Comment by PureDude** [comment] 2017-04-27 08:53
Thank you for your quick response! I don't want to use the annotations in a doughnut chart but in a line chart on the same page. So there is currently no way or workaround to use the annotation plugin in a line chart on the same page with a donut chart without annotations?

**Comment by etimberg** [comment] 2017-04-27 11:20
@PureDude if you're using Chart.js v2.5.0, you could add the plugin to only that charts that need it rather than for all charts on the page https://github.com/chartjs/Chart.js/blob/master/docs/developers/plugins.md#using-plugins

**Comment by PureDude** [comment] 2017-04-28 07:30
@etimberg Thx for this info! I know it's off topic but do you have an example for me how I can include the annotation plugin in this way? All my attempts ended with errors...

**Comment by etimberg** [comment] 2017-04-28 10:40
That's a good question. You may need a fork because the global registration happens automatically :/ @compwright thoughts?

**Comment by chrisyaxley** [comment] 2017-05-18 13:34
Any update on the fix for this? I haven't been able to get the plugin include working either.

**Comment by compwright** [comment] 2017-05-20 14:24
@PureDude can you verify if https://github.com/chartjs/chartjs-plugin-annotation/pull/69 fixes you issue?

H/T @chrisyaxley

**Comment by compwright** [comment] 2017-05-20 15:02
Duplicate of #49

**Closed by compwright** 2017-05-20 15:02 UTC
Labels: duplicate

**Comment by PureDude** [comment] 2017-05-22 08:49
@compwright I have tested and #69 (already included in Version 0.5.5) fixes the issue! Many thanks!
