### ISSUE TITLE
Annotation on duplicated labels

### ISSUE THREAD

**Issue by AmirHossein** [chartjs/chartjs-plugin-annotation#167] opened 2019-06-30 10:16 UTC
I have duplicated labels on chart and can't set annotation for specified label; This plugin uses label value and draws annotation on first matching label. It will be great if i could also set value (or min/max) by label-index or callback.
In sample below i can't set annotation for Second "February" column:
https://codepen.io/anon/pen/wLydrg?editors=0010
```javascript
var chartData = {
  labels: ["January", "February", "March", "April", "May", "June", "July", "January", "February", "March"],
  datasets: [{type: "bar", data: [10, 14, 9, 10, 13, 17, 15, 16, 10, 12]}]
};
window.onload = function() {
  var ctx = document.getElementById("canvas").getContext("2d");
  window.myMixedChart = new Chart(ctx, {
    type: "bar",
    data: chartData,
    options: {
      responsive: true,
      annotation: {
        annotations: [
          {
            type: "line",
            mode: "vertical",
            scaleID: "x-axis-0",
            value: "February",
            borderColor: "black",
            borderWidth: 5,
            label: { enabled: true}
          }
        ]
      }
    }
  });
};
```

**Comment by etimberg** [comment] 2021-03-08 01:29
Duplicate of #98

**Closed by etimberg** 2021-03-08 01:29 UTC
Labels: enhancement
