### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'borderWidth') in FilamentPHP

### ISSUE THREAD

**Issue by mahjoubkzbr** [chartjs/chartjs-plugin-annotation#960] opened 2024-12-18 19:14 UTC
Hello, I am currently trying to integrate the plugin into my filamentphp application. Currently i have this error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'borderWidth')
    at resolveLabelElementProperties (chartjs-plugin-annotation.js?v=96069a54:1670:31)
    at LineAnnotation.resolveElementProperties (chartjs-plugin-annotation.js?v=96069a54:1498:29)
    at updateElements (chartjs-plugin-annotation.js?v=96069a54:2158:32)
    at Object.afterUpdate (chartjs-plugin-annotation.js?v=96069a54:2305:5)
    at j (chart.js?v=3.2.113.0:1:696)
    at xr._notify (chart.js?v=3.2.113.0:1:108756)
    at xr.notify (chart.js?v=3.2.113.0:1:108560)
    at xe.notifyPlugins (chart.js?v=3.2.113.0:1:126648)
    at xe.update (chart.js?v=3.2.113.0:1:119751)
    at new xe (chart.js?v=3.2.113.0:1:115890)
```
    
#953 Mentions a similar issue. It got resolved by properly registering the plugin in angular. Since i am using php, the presented approach won't work for me.

These are my chart options:

```
protected function getOptions(): array|RawJs|null
    {
        return [
            'indexAxis' => 'y',
            'plugins' => [
                'legend' => [
                    'display' => true,
                ],
                'annotation' => [
                    'annotations' => [
                        'line1' => [
                            'type' => 'line',
                            'xMin' => 10,
                            'xMax' => 10,
                            'borderColor' => 'rgb(255, 99, 132)',
                            'borderWidth' => 2,
                        ]
                    ]
                ]
            ],
            'scales' => [
                'y' => [
                    'stacked' => true, // Enable stacking on y-axis
                ],
                'x' => [
                    'ticks' => [
                        'stepSize' => 1,
                    ]
                ]
            ],
        ];
    }
```

This is my registration according to the filamentphp documentation

filament-chart-js-plugins.js
```
import annotationPlugin from 'chartjs-plugin-annotation';
import { Chart } from 'chart.js';

Chart.register(annotationPlugin);
window.filamentChartJsPlugins ??= []
window.filamentChartJsPlugins.push(annotationPlugin)
```

vite.config.js
```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/css/filament/admin/theme.css',
                'resources/js/filament-chart-js-plugins.js'
            ],
            refresh: true,
        }),
    ],
});
```

AppServiceProvider.php
```
        FilamentAsset::register([
            Js::make('chart-js-plugins', Vite::asset('resources/js/filament-chart-js-plugins.js'))->module(),
        ]);
```

Any help is highly appreciated! Thanks in advance!

**Comment by stockiNail** [comment] 2024-12-19 07:20
@kouzkoko I had a quick look and I found the following discussion in filamentphp: https://github.com/filamentphp/filament/discussions/11472

Maybe you have already read, and apologize for that.

**Comment by mahjoubkzbr** [comment] 2024-12-19 11:55
> @kouzkoko I had a quick look and I found the following discussion in filamentphp: [filamentphp/filament#11472](https://github.com/filamentphp/filament/discussions/11472)
> 
> Maybe you have already read, and apologize for that.

actually i haven't read it until now. but unfortunately the thread didn't provide a solution for me...

**Comment by stockiNail** [comment] 2024-12-20 08:08
@kouzkoko  I had a look to the codebase of filament.

The issue is on fileament side, here:

https://github.com/filamentphp/filament/blob/96afca6a122875c19237ab14b168abe6616b94d1/packages/widgets/resources/js/components/chart.js#L84-L90

filament didn't implement the Global plugins and when you add the annotation plugin to `filamentChartJsPlugins`, this array is set as inline plugin of chart instance.

I would suggest to add an issue as enhancement to filament repo.

Nevertheless, even if I don't know how filament is working, you could try to remove the push the array of annotation plugin, leaving only the Chart.register.

Let me know if it works.

**Comment by stockiNail** [comment] 2024-12-21 10:36
@kouzkoko I assume that the proposed solution is working. ;) Let me close this issue but feel free to re open if needed.

**Closed as completed by stockiNail** 2024-12-21 10:36 UTC
Labels: help wanted
