### ISSUE TITLE
Doesn't work with 2.8.0

### ISSUE THREAD

**Issue by Svetomechc** [chartjs/chartjs-plugin-annotation#156] opened 2019-03-18 09:15 UTC
Is there any workaround to get the plugin working with chart.js 2.8.0?

**Comment by Svetomechc** [comment] 2019-03-18 09:23
So, it seems to me that 2.7.0 breaks lines and 2.8.0 breaks boxes. Any plans on fixing that?

**Comment by benmccann** [comment] 2019-03-19 14:51
@Svetomechc there isn't anyone who is actively working on this plugin, but if you send a PR to fix it then I will review it

**Comment by nullpointer77** [comment] 2019-03-19 14:54
@Svetomechc For what it's worth, i ended up abandoning this plugin as well as the draggable plugin as it's pretty simple to just create your own custom chartjs plugins per their documentation.  If you really need draggable functionality D3 has a pretty solid implementation you can use.

**Comment by kurkle** [comment] 2019-03-19 15:07
I'm using it with 2.8.0, how does it break for you?

**Comment by Svetomechc** [comment] 2019-03-19 15:11
@benmccann not so sure of my JS skills (:

@nullpointer77 might try that

@kurkle I use it like so (type: 'box'):

```ts
    const annotations = this.selectedCip.cipSteps.map(v => {

      const color = new Color('#' + v.cipStepType.color);
      color.a = 0.3;
      return {
        drawTime: 'beforeDatasetsDraw',
        type: 'box',
        xScaleID: 'x1',
        yScaleID: 'dummy',
        xMin: v.start,
        xMax: v.end,
        yMin: 0,
        yMax: 1,
        backgroundColor: color.toRgba(),
        borderWidth: 0,
      };
    });
    this.lineChartOptions.annotation = { annotations: annotations };
```

**Comment by alexis-landrieu-avanade** [comment] 2019-04-05 07:48
Hello @Svetomechc , could you share your imports statement ? 

For angular by example we need to follow these steps : 

```typescript
import * as ChartAnnotation from 'chartjs-plugin-annotation';

ngOnInit() {
  let caPlugin = ChartAnnotation;
  caPlugin["id"]="annotation";
  Chart.pluginService.register(caPlugin);
}
```

**Comment by Svetomechc** [comment] 2019-04-05 08:42
@alexis-landrieu-avanade thank you!

**Comment by flaushi** [comment] 2019-04-17 19:28
Hmm, for me the annotations do work with 2.8.0 - at least as long as I do not resize the canvas...

**Comment by KayHS** [comment] 2019-06-05 14:17
Im also having issues with this even after following @alexis-landrieu-avanade suggestion

**Comment by Svetomechc** [comment] 2019-06-05 14:31
Still works for me with @alexis-landrieu-avanade fix:

![image](https://user-images.githubusercontent.com/36156020/58964293-50732880-87b7-11e9-8ef5-5f3ba5d52ea3.png)


But recently **chartjs-plugin-zoom** stopped working. Currently investigating why...

**Comment by KayHS** [comment] 2019-06-05 14:38
```
    "chart.js": "^2.8.0",
    "chartjs-plugin-annotation": "^0.5.7",
```

This is my npm package, i think the version is compatible?

**Comment by KayHS** [comment] 2019-06-05 14:52
I fixed it, i had 4 problems. 

1.  You have to define the plugin
```
   plugins: [ChartAnnotation],
```
2. Where to place the annotation, the documentation makes this very confusing by showing it within options.plugins, when actually it only works as as a child of options.

3. the annotation value it of type int it will not work if mode if vertical, but it will work if mode if horizontal. because my line was vertical i had to convert this value to a string.

4. If you are using types its going to complain about annotations so you should add `as ChartOptions`

```
     const myChart = new Chart(this.ctx, {
            type: 'line',
            plugins: [ChartAnnotation],
            data: {
                labels: stringLabels,
                datasets: [{
                    fill: true,
                    lineTension: 0.5,
                    pointRadius: 0, // Removes indiviual points/tooltips
                    borderWidth: 1,
                    label: 'Monthly Spending',
                    data: data,
                    backgroundColor: 'rgb(124,190,235,0.6)',
                    borderColor: 'rgb(63,81,181)'
                }]
            },
            options: {
                annotation: {
                    annotations: [
                        {
                            type: 'line',
                            mode: 'vertical',
                            scaleID: 'x-axis-0',
                            value: payday.toString(),
                            borderColor: 'red',
                            borderWidth: 2,
                        }
                    ]
                }
            } as ChartOptions
        });
```

**Comment by benmccann** [comment] 2019-06-05 15:05
The issue is that the README shows the setup for the code in `master` (https://github.com/chartjs/chartjs-plugin-annotation/pull/130), but the last time a new version was released was Oct 2017. We should release a new version of the plugin to fix it

**Comment by benmccann** [comment] 2019-06-05 15:07
Although it looks like we might need a fix first: https://github.com/chartjs/chartjs-plugin-annotation/pull/130#issuecomment-474411821

If anyone wants to send a fix, I can help get it reviewed and merged and a new version released

**Comment by jazzy1986** [comment] 2019-09-30 05:27
> I fixed it, i had 4 problems.
> 
> 1. You have to define the plugin
> 
> ```
>    import * as ChartAnnotation from 'chartjs-plugin-annotation';
>    ...
>    plugins: [ChartAnnotation],
> ```
> 
> 1. Where to place the annotation, the documentation makes this very confusing by showing it within options.plugins, when actually it only works as as a child of options.
> 2. When the annotation value is of type int, it will not work if mode is vertical, but it will work if mode if horizontal. because my line was vertical i had to convert this value to a string.
> 3. If you are using types its going to complain about annotations so you should add `as ChartOptions`
> 
> ```
>      const myChart = new Chart(this.ctx, {
>             type: 'line',
>             plugins: [ChartAnnotation],
>             data: {
>                 labels: stringLabels,
>                 datasets: [{
>                     fill: true,
>                     lineTension: 0.5,
>                     pointRadius: 0, // Removes indiviual points/tooltips
>                     borderWidth: 1,
>                     label: 'Monthly Spending',
>                     data: data,
>                     backgroundColor: 'rgb(124,190,235,0.6)',
>                     borderColor: 'rgb(63,81,181)'
>                 }]
>             },
>             options: {
>                 annotation: {
>                     annotations: [
>                         {
>                             type: 'line',
>                             mode: 'vertical',
>                             scaleID: 'x-axis-0',
>                             value: payday.toString(),
>                             borderColor: 'red',
>                             borderWidth: 2,
>                         }
>                     ]
>                 }
>             } as ChartOptions
>         });
> ```

thanks, you save my life, take me whole morning to solve this, love you so much. it actually need to be inside OPTIONS not beside it. Chart.js document is suck

**Comment by iamjonmiller** [comment] 2019-10-15 17:39
Just trying to import this plugin spits out this error in the chrome console:

`chartjs-plugin-annotation.min.js:10 Uncaught TypeError: Cannot read property 'Annotation' of undefined
    at Object.6../annotation.js (chartjs-plugin-annotation.min.js:10)
    at o (chartjs-plugin-annotation.min.js:10)
    at e (chartjs-plugin-annotation.min.js:10)
    at chartjs-plugin-annotation.min.js:10
6../annotation.js @ chartjs-plugin-annotation.min.js:10
o @ chartjs-plugin-annotation.min.js:10
e @ chartjs-plugin-annotation.min.js:10
(anonymous) @ chartjs-plugin-annotation.min.js:10
`

Also using with 2.8.0

**Comment by kurkle** [comment] 2019-10-16 11:07
> Just trying to import this plugin spits out this error in the chrome console:
> 
> `chartjs-plugin-annotation.min.js:10 Uncaught TypeError: Cannot read property 'Annotation' of undefined at Object.6../annotation.js (chartjs-plugin-annotation.min.js:10) at o (chartjs-plugin-annotation.min.js:10) at e (chartjs-plugin-annotation.min.js:10) at chartjs-plugin-annotation.min.js:10 6../annotation.js @ chartjs-plugin-annotation.min.js:10 o @ chartjs-plugin-annotation.min.js:10 e @ chartjs-plugin-annotation.min.js:10 (anonymous) @ chartjs-plugin-annotation.min.js:10 `
> 
> Also using with 2.8.0 and cdn here https://cdnjs.com/libraries/chartjs-plugin-annotation

Did you import Chart.js before the plugin?

**Comment by iamjonmiller** [comment] 2019-10-17 17:11
> > Just trying to import this plugin spits out this error in the chrome console:
> > `chartjs-plugin-annotation.min.js:10 Uncaught TypeError: Cannot read property 'Annotation' of undefined at Object.6../annotation.js (chartjs-plugin-annotation.min.js:10) at o (chartjs-plugin-annotation.min.js:10) at e (chartjs-plugin-annotation.min.js:10) at chartjs-plugin-annotation.min.js:10 6../annotation.js @ chartjs-plugin-annotation.min.js:10 o @ chartjs-plugin-annotation.min.js:10 e @ chartjs-plugin-annotation.min.js:10 (anonymous) @ chartjs-plugin-annotation.min.js:10 `
> > Also using with 2.8.0 and cdn here https://cdnjs.com/libraries/chartjs-plugin-annotation
> 
> Did you import Chart.js before the plugin?

Apparently not, I thought I had tried that. Combined with _KayHS_ solution above (manually importing) I have annotations working on 2.8.0 now. Thanks!

**Comment by sukensheth** [comment] 2019-11-14 10:30
Hi. I'm trying to import chartjs-annotation-plugin in my Angular project. Even after the npm install and 
import * as ChartAnnotation from 'chartjs-plugin-annotation';

I am getting this : 
Could not find a declaration file for module 'chartjs-plugin-annotation'. 'c:/XRay/xray/node_modules/chartjs-plugin-annotation/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/chartjs-plugin-annotation` if it exists or add a new declaration (.d.ts) file containing `declare module 'chartjs-plugin-annotation';`

**Comment by sfentress** [comment] 2020-01-08 15:25
Thank you all for this helpful thread. I'll just add some details about the changes I had to make for those who are upgrading to 2.8.0 and using React, which hasn't been touched on above:

1. Add `ChartAnnotation` to the `plugins` field of your chart component:

```diff
-import "chartjs-plugin-annotation";
+import * as ChartAnnotation from "chartjs-plugin-annotation";

...

<Scatter
  data={data}
  options={options}
+  plugins={[ChartAnnotation]}
/>
```

2. (Already mentioned above, but adding here for clarity): Move the annotation plugin definition up a level, out from the `plugins` section of `options` . Shown here with TypeScript:

```diff
const defaultOptions: ChartOptions = {
  title: ...
- plugins: {
-   annotation: {
-     drawTime: "afterDraw",
-     events: ["click", "mouseenter", "mouseleave"],
-     annotations: [ ... ]
-   }
+ annotation: {
+   drawTime: "afterDraw",
+   events: ["click", "mouseenter", "mouseleave"],
+   annotations: [ ... ]
+ }
-};
+} as ChartOptions;
```
3. For TypeScript, declare the module in an index.d.ts file (to answer @sukensheth 's question):

```diff
+declare module "chartjs-plugin-annotation";
```
4. Maybe unrelated, but the label position `"top"` no longer worked after the upgrade. I had to hack it with `label: { position: "bottom", yAdjust: 300}`.

**Comment by philippfrank** [comment] 2020-09-28 13:03
@benmccann 

> If anyone wants to send a fix, I can help get it reviewed and merged and a new version released

Are you still a maintainer of this project? Could you release a new version?

**Comment by abhijiy** [comment] 2020-12-02 06:57
My functionality is describe below:
 After click on line chart I need to show the annotation line.I have included annotation plugin. But it is not working.Annotation plugin is not called.

**Comment by etimberg** [comment] 2021-03-08 01:59
Closing this thread as it contained a bunch of different issues that appear to be resolved

1. New versions (1.0.0-beta.1 to 1.0.0-beta.4) released to work with chart.js v3.0.0-beta.*
2. Typescript types now ship with the plugin
3. Documentation issues tracked elsewhere (e.g. #336 and #343)

**Closed by etimberg** 2021-03-08 01:59 UTC
Labels: bug, chart.js version 2
